# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-File-PDB
version:      0.21
version_from: PDB.pm
installdirs:  site
requires:
    Chemistry::MacroMol:           0.05
    Chemistry::Mol:                0.30

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
